language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
gemfile:
  - gemfiles/rails_3.0.0.gemfile
  - gemfiles/rails_3.1.0.gemfile
  - gemfiles/rails_3.2.0.gemfile
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.2.0.gemfile
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails_4.0.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails_3.2.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails_3.1.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails_3.0.0.gemfile
